# Generated by Django 5.2.1 on 2025-09-10 15:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LAB', 'Labor'), ('MAT', 'Materials'), ('EQP', 'Equipment'), ('SUB', 'Subcontractor'), ('OTH', 'Other')], max_length=3)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LAB', 'Labor'), ('MAT', 'Materials'), ('EQP', 'Equipment'), ('SUB', 'Subcontractor'), ('OTH', 'Other')], max_length=3)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_incurred', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_incurred'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_source', models.CharField(choices=[('GC', 'General Contractor'), ('DC', 'Direct Client')], max_length=20)),
                ('project_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('project_category', models.CharField(blank=True, choices=[('PUB', 'Public'), ('PRI', 'Private'), ('REN', 'Renovation'), ('NEW', 'New Build')], max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=300)),
                ('gps_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('city_province', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('approved_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('expense', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('site_engineer', models.CharField(blank=True, max_length=200, null=True)),
                ('subcontractors', models.TextField(blank=True, null=True)),
                ('contract_agreement', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('permits_licenses', models.FileField(blank=True, null=True, upload_to='permits/')),
                ('status', models.CharField(choices=[('PL', 'Planned'), ('OG', 'Ongoing'), ('CP', 'Completed'), ('CN', 'Cancelled')], default='PL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('progress', models.DecimalField(decimal_places=2, default=0, help_text='Overall project progress (%)', max_digits=5)),
            ],
            options={
                'ordering': ['-created_at', 'project_name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_data', models.JSONField()),
                ('project_source', models.CharField(choices=[('GC', 'General Contractor'), ('DC', 'Direct Client')], max_length=20)),
                ('project_id_placeholder', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('PL', 'Pending'), ('AP', 'Approved'), ('RJ', 'Rejected')], default='PL', max_length=2)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStagingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PL', 'Pending'), ('AP', 'Approved'), ('RJ', 'Rejected')], max_length=2)),
                ('comments', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Type',
                'verbose_name_plural': 'Project Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FundAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_allocated', models.DateField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('project_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='project_profiling.projectbudget')),
            ],
            options={
                'ordering': ['-date_allocated'],
            },
        ),
    ]
