# Generated by Django 5.2.1 on 2025-09-10 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('manage_client', '0002_initial'),
        ('project_profiling', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcost',
            name='linked_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.projecttask'),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_assigned', to='authentication.userprofile'),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='manage_client.client'),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to='authentication.userprofile'),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='project_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userprofile'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project_profiling.projectprofile'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='project_profiling.projectprofile'),
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='project_profiling.projectprofile'),
        ),
        migrations.AddField(
            model_name='projectstaging',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userprofile'),
        ),
        migrations.AddField(
            model_name='projectstaginghistory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userprofile'),
        ),
        migrations.AddField(
            model_name='projectstaginghistory',
            name='project_staging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='project_profiling.projectstaging'),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userprofile'),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='project_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='project_profiling.projecttype'),
        ),
    ]
