# Generated by Django 5.2.1 on 2025-09-11 05:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0002_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectbudget',
            options={'ordering': ['scope__name', 'category']},
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='scope',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to='scheduling.projectscope'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='projectbudget',
            unique_together={('scope', 'category')},
        ),
    ]
