# Generated by Django 5.2.1 on 2025-09-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0003_alter_projectbudget_options_projectbudget_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbudget',
            name='category_other',
            field=models.CharField(blank=True, help_text='Specify if category is Other', max_length=255, null=True),
        ),
    ]
