# Generated by Django 5.2.1 on 2025-09-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0004_projectbudget_category_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundallocation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundallocation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
