# Generated by Django 5.2.1 on 2025-09-12 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('project_profiling', '0005_fundallocation_deleted_at_fundallocation_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('material', 'Material Purchase'), ('labor', 'Labor Payment'), ('equipment', 'Equipment Rental'), ('service', 'Service/Contractor'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('expense_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='project_profiling.projectbudget')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='project_profiling.projectprofile')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
