# Generated by Django 5.2.1 on 2025-09-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0006_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_other',
            field=models.CharField(blank=True, help_text='Specify if expense type is other', max_length=255, null=True),
        ),
    ]
