# Generated by Django 5.2.1 on 2025-09-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0007_expense_expense_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprofile',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('DR', 'Draft'), ('PL', 'Planned'), ('OG', 'Ongoing'), ('CP', 'Completed'), ('CN', 'Cancelled')], default='PL', max_length=20),
        ),
    ]
