# Generated by Django 5.2.1 on 2025-09-17 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('project_profiling', '0008_alter_projectprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'EG'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_approved', to='authentication.userprofile'),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='True if this is a draft'),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='submitted_for_approval',
            field=models.BooleanField(default=False, help_text='True if submitted for approval'),
        ),
    ]
