# Generated by Django 5.2.1 on 2025-09-17 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('project_profiling', '0009_projectprofile_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstaging',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstaging',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'EG'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_projects_approved', to='authentication.userprofile'),
        ),
        migrations.AddField(
            model_name='projectstaging',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='True if this is a draft'),
        ),
        migrations.AddField(
            model_name='projectstaging',
            name='submitted_for_approval',
            field=models.BooleanField(default=False, help_text='True if submitted for approval'),
        ),
    ]
