# Generated by Django 5.2.1 on 2025-09-21 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_projectassignment_options_and_more'),
        ('project_profiling', '0010_projectstaging_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='foreman',
            field=models.ForeignKey(blank=True, help_text='Foreman', limit_choices_to={'role': 'FM', 'status': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_foreman', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='number_of_laborers',
            field=models.PositiveIntegerField(default=0, help_text='Number of laborers assigned to this project'),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='project_in_charge',
            field=models.ForeignKey(blank=True, help_text='Project In Charge', limit_choices_to={'role': 'PIC', 'status': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_pic', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='quality_assurance_officer',
            field=models.ForeignKey(blank=True, help_text='Quality Assurance Officer', limit_choices_to={'role': 'QA', 'status': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_qa', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='quality_officer',
            field=models.ForeignKey(blank=True, help_text='Quality Officer', limit_choices_to={'role': 'QO', 'status': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_qo', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='safety_officer',
            field=models.ForeignKey(blank=True, help_text='Safety Officer', limit_choices_to={'role': 'SO', 'status': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_so', to='employees.employee'),
        ),
    ]
