# Generated by Django 5.2.1 on 2025-10-13 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('project_profiling', '0011_projectprofile_foreman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbudget',
            name='category',
            field=models.CharField(choices=[('LAB', 'Labor'), ('MAT', 'Materials'), ('EQP', 'Equipment'), ('SUB', 'Subcontractor'), ('MOB', 'Mobilization'), ('OTH', 'Other')], max_length=3),
        ),
        migrations.AlterField(
            model_name='projectcost',
            name='category',
            field=models.CharField(choices=[('LAB', 'Labor'), ('MAT', 'Materials'), ('EQP', 'Equipment'), ('SUB', 'Subcontractor'), ('MOB', 'Mobilization'), ('OTH', 'Other')], max_length=3),
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Contract Agreement'), ('PERMIT', 'Permit/License'), ('PROGRESS', 'Progress Report'), ('COSTING', 'Costing Proof'), ('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('TECHNICAL', 'Technical Drawing'), ('PHOTO', 'Project Photo'), ('OTHER', 'Other')], max_length=20)),
                ('document_type_other', models.CharField(blank=True, help_text='Specify if type is Other', max_length=100)),
                ('project_stage', models.CharField(choices=[('INIT', 'Initiation'), ('PLAN', 'Planning'), ('EXEC', 'Execution'), ('MONITOR', 'Monitoring'), ('CLOSE', 'Closing')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='project_documents/')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_mandatory', models.BooleanField(default=False, help_text='Required document for this project')),
                ('is_archived', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='project_profiling.projectprofile')),
                ('replaces', models.ForeignKey(blank=True, help_text='Previous version of this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='project_profiling.projectdocument')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['project', 'document_type'], name='project_pro_project_4344b1_idx'), models.Index(fields=['project', 'project_stage'], name='project_pro_project_40c6bb_idx'), models.Index(fields=['is_mandatory', 'is_archived'], name='project_pro_is_mand_866557_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubcontractorExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcontractor_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('contract_number', models.CharField(blank=True, max_length=100)),
                ('scope_of_work', models.TextField()),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PEND', 'Pending'), ('PROG', 'In Progress'), ('COMP', 'Completed'), ('CANC', 'Cancelled')], default='PEND', max_length=4)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='subcontractor_contracts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userprofile')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_details', to='project_profiling.expense')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_expenses', to='project_profiling.projectprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='project_pro_project_3d4d00_idx'), models.Index(fields=['subcontractor_name'], name='project_pro_subcont_d59fb3_idx')],
            },
        ),
    ]
