# Generated by Django 5.2.1 on 2025-10-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0013_migrate_documents_to_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for searchability', max_length=500),
        ),
    ]
