# Generated by Django 5.2.1 on 2025-10-14 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('project_profiling', '0014_add_tags_to_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION', 'Needs Revision')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to='authentication.userprofile'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection or revision request'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='version_notes',
            field=models.TextField(blank=True, help_text='What changed in this version'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='authentication.userprofile'),
        ),
        migrations.CreateModel(
            name='MobilizationCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TRANSPORT', 'Equipment Transportation'), ('SETUP', 'Site Setup & Preparation'), ('TEMP_FAC', 'Temporary Facilities'), ('PERMITS', 'Permits & Bonds'), ('SAFETY', 'Safety Equipment & Signage'), ('UTILITIES', 'Temporary Utilities Connection'), ('SURVEY', 'Survey & Layout'), ('OTHER', 'Other Mobilization Costs')], max_length=10)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(default='lot', help_text='e.g., trip, set, piece, lot', max_length=50)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='mobilization_invoices/')),
                ('date_incurred', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilization_costs', to='project_profiling.projectprofile')),
            ],
            options={
                'ordering': ['project', 'category', 'date_incurred'],
                'indexes': [models.Index(fields=['project', 'category'], name='project_pro_project_b727e0_idx'), models.Index(fields=['date_incurred'], name='project_pro_date_in_f1a7af_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubcontractorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.PositiveIntegerField(help_text='Sequential payment number')),
                ('milestone_description', models.TextField(help_text='What milestone/work phase this payment covers')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('CHECK', 'Check'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash'), ('CREDIT', 'Credit/Debit Card'), ('OTHER', 'Other')], default='BANK', max_length=10)),
                ('payment_date', models.DateField()),
                ('reference_number', models.CharField(blank=True, help_text='Check number, transaction ID, etc.', max_length=100)),
                ('status', models.CharField(choices=[('PEND', 'Pending Approval'), ('APPR', 'Approved'), ('PAID', 'Paid'), ('CANC', 'Cancelled')], default='PEND', max_length=4)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='subcontractor_receipts/')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='subcontractor_invoices/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to='authentication.userprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to='authentication.userprofile')),
                ('subcontractor_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='project_profiling.subcontractorexpense')),
            ],
            options={
                'ordering': ['subcontractor_expense', 'payment_number'],
                'indexes': [models.Index(fields=['subcontractor_expense', 'status'], name='project_pro_subcont_f5861f_idx'), models.Index(fields=['payment_date'], name='project_pro_payment_5fe3e5_idx')],
                'unique_together': {('subcontractor_expense', 'payment_number')},
            },
        ),
    ]
