# Generated by Django 5.2.1 on 2025-10-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0015_projectdocument_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractorexpense',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
