# Generated by Django 5.2.1 on 2025-10-15 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0016_make_start_date_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='project_staging',
            field=models.ForeignKey(blank=True, help_text='Link to pending project if document uploaded before approval', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='project_profiling.projectstaging'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='project_profiling.projectprofile'),
        ),
    ]
