# Generated by Django 5.2.5 on 2025-10-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0017_add_project_staging_to_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='lot_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lot size in square meters', max_digits=10, null=True),
        ),
    ]
