# Generated by Django 5.2.1 on 2025-10-16 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0019_complexitymultiplier_locationmultiplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='boq_file_processed',
            field=models.BooleanField(default=False, help_text='Whether BOQ file has been processed for cost extraction'),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='cost_data_contributed',
            field=models.BooleanField(default=False, help_text="Whether this project's cost data has been contributed to ProjectType learning"),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='extracted_cost_breakdown',
            field=models.JSONField(blank=True, help_text='Cost breakdown extracted from BOQ (materials, labor, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='extracted_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost extracted from BOQ documents', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='last_cost_update',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last cost data update', null=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='total_projects_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of projects contributing to cost data'),
        ),
        migrations.CreateModel(
            name='ProjectTypeCostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_size', models.DecimalField(decimal_places=2, help_text='Lot size in square meters', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total project cost in PHP', max_digits=15)),
                ('cost_per_sqm', models.DecimalField(decimal_places=2, help_text='Cost per square meter', max_digits=10)),
                ('materials_cost', models.DecimalField(decimal_places=2, default=0, help_text='Materials cost', max_digits=15)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, help_text='Labor cost', max_digits=15)),
                ('equipment_cost', models.DecimalField(decimal_places=2, default=0, help_text='Equipment cost', max_digits=15)),
                ('permits_cost', models.DecimalField(decimal_places=2, default=0, help_text='Permits and fees cost', max_digits=15)),
                ('contingency_cost', models.DecimalField(decimal_places=2, default=0, help_text='Contingency cost', max_digits=15)),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=0, help_text='Overhead cost', max_digits=15)),
                ('location', models.CharField(blank=True, help_text='Project location', max_length=200)),
                ('project_category', models.CharField(blank=True, help_text='Project category (PUB, PRI, REN, NEW)', max_length=10)),
                ('complexity_level', models.CharField(choices=[('low_end', 'Low End'), ('mid_range', 'Mid Range'), ('high_end', 'High End')], default='mid_range', help_text='Project complexity level', max_length=10)),
                ('source', models.CharField(choices=[('boq_upload', 'BOQ Upload'), ('project_completion', 'Project Completion'), ('manual_entry', 'Manual Entry')], default='boq_upload', help_text='Source of cost data', max_length=20)),
                ('is_approved', models.BooleanField(default=False, help_text='Whether this cost data is approved for learning')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When this data was uploaded')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When this data was approved', null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_contributions', to='project_profiling.projectprofile')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_history', to='project_profiling.projecttype')),
            ],
            options={
                'verbose_name': 'Project Type Cost History',
                'verbose_name_plural': 'Project Type Cost Histories',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
