# Generated by Django 5.2.1 on 2025-10-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0022_add_project_role_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttypecosthistory',
            name='project_role',
            field=models.CharField(choices=[('general_contractor', 'General Contractor'), ('subcontractor', 'Subcontractor')], default='general_contractor', help_text='Role of the company in this project', max_length=20),
        ),
    ]
