# Generated by Django 5.2.1 on 2025-09-10 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('project_profiling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.CharField(blank=True, max_length=50, null=True)),
                ('accomplished_to_date', models.CharField(blank=True, max_length=50, null=True)),
                ('accomplished_before', models.CharField(blank=True, max_length=50, null=True)),
                ('accomplished_this_period', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='project_profiling.projectprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates_made', to='authentication.userprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates_reviewed', to='authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='progress_proofs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='scheduling.progressupdate')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight contribution to project (%)', max_digits=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='project_profiling.projectprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('manhours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of task relative to its scope (%)', max_digits=5)),
                ('progress', models.DecimalField(decimal_places=2, default=0, help_text='Progress % reported by Project Manager', max_digits=5)),
                ('is_completed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PL', 'Planned'), ('OG', 'Ongoing'), ('CP', 'Completed')], default='PL', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Project Manager responsible for updating this task', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userprofile')),
                ('dependencies', models.ManyToManyField(blank=True, to='scheduling.projecttask')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project_profiling.projectprofile')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scheduling.projectscope')),
            ],
        ),
        migrations.AddField(
            model_name='progressupdate',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='scheduling.projecttask'),
        ),
        migrations.CreateModel(
            name='SystemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('O', 'On-Demand')], max_length=1)),
                ('file', models.FileField(upload_to='auto_reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_reports', to='project_profiling.projectprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_costs', to='project_profiling.projectcost')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_costs', to='scheduling.projecttask')),
            ],
        ),
    ]
