# Generated by Django 5.2.1 on 2025-09-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectscope',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
