# Generated by Django 5.2.1 on 2025-10-15 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_equipment', '0001_initial'),
        ('scheduling', '0002_projectscope_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskManpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_type', models.CharField(choices=[('SKILLED', 'Skilled Labor'), ('UNSKILLED', 'Unskilled Labor'), ('ENGINEER', 'Engineer'), ('FOREMAN', 'Foreman'), ('OPERATOR', 'Equipment Operator')], max_length=20)),
                ('description', models.CharField(help_text="Description of labor role (e.g., 'Carpenter', 'Mason', 'Electrician')", max_length=255)),
                ('number_of_workers', models.IntegerField(default=1)),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Daily wage per worker', max_digits=15)),
                ('days_needed', models.IntegerField(help_text='Number of days this labor is needed')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_manpower', to='scheduling.projecttask')),
            ],
            options={
                'verbose_name': 'Task Manpower Allocation',
                'verbose_name_plural': 'Task Manpower Allocations',
            },
        ),
        migrations.CreateModel(
            name='TaskEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_type', models.CharField(choices=[('RENTAL', 'Rental'), ('OWNED', 'Owned/Company')], max_length=10)),
                ('quantity', models.IntegerField(default=1, help_text='Number of units needed')),
                ('days_needed', models.IntegerField(help_text='Number of days equipment is needed for this task')),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Daily rental/usage cost', max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_allocations', to='materials_equipment.equipment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_equipment', to='scheduling.projecttask')),
            ],
            options={
                'verbose_name': 'Task Equipment Allocation',
                'verbose_name_plural': 'Task Equipment Allocations',
                'unique_together': {('task', 'equipment')},
            },
        ),
        migrations.CreateModel(
            name='TaskMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.DecimalField(decimal_places=2, help_text='Quantity of this material needed for this task', max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit at time of allocation', max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_allocations', to='materials_equipment.projectmaterial')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_materials', to='scheduling.projecttask')),
            ],
            options={
                'verbose_name': 'Task Material Allocation',
                'verbose_name_plural': 'Task Material Allocations',
                'unique_together': {('task', 'material')},
            },
        ),
    ]
