# Generated by Django 5.2.1 on 2025-10-15 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_equipment', '0001_initial'),
        ('scheduling', '0003_taskmanpower_taskequipment_taskmaterial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskmaterial',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='taskmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_allocations', to='materials_equipment.material'),
        ),
    ]
