# Generated by Django 5.2.1 on 2025-10-15 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0017_add_project_staging_to_documents'),
        ('scheduling', '0004_alter_taskmaterial_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, help_text='Budget allocated to this scope', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_budgets', to='project_profiling.projectprofile')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='scheduling.projectscope')),
            ],
            options={
                'verbose_name': 'Scope Budget',
                'verbose_name_plural': 'Scope Budgets',
                'unique_together': {('project', 'scope')},
            },
        ),
    ]
