# Generated by Django 5.2.1 on 2025-09-17 16:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('project_profiling', '0010_projectstaging_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('employee_id', models.CharField(help_text='Company employee ID', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(choices=[('PM', 'Project Manager'), ('PIC', 'Project In Charge'), ('SO', 'Safety Officer'), ('QA', 'Quality Assurance Officer'), ('QO', 'Quality Officer'), ('FM', 'Foreman'), ('LB', 'Labor')], max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], default='active', max_length=15)),
                ('hire_date', models.DateField()),
                ('contract_end_date', models.DateField(blank=True, help_text='Contract expiration date', null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('contract_expiry_notified', models.BooleanField(default=False, help_text='Has been notified about contract expiry')),
                ('auto_deactivated', models.BooleanField(default=False, help_text='Was automatically deactivated due to contract expiry')),
                ('labor_count', models.PositiveIntegerField(default=1, help_text='For labor roles, this can represent number of workers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='authentication.userprofile')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_lead', models.BooleanField(default=False, help_text='Is this employee the lead for this role on this project?')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_profiling.projectprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='employees_e_employe_514cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['role', 'status'], name='employees_e_role_560693_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectassignment',
            unique_together={('employee', 'project')},
        ),
    ]
