# Generated by Django 5.2.1 on 2025-09-18 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('employees', '0001_initial'),
        ('project_profiling', '0010_projectstaging_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectassignment',
            options={'ordering': ['-assigned_date']},
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='project_profiling.projectprofile'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['contract_end_date'], name='employees_e_contrac_2e1ba1_idx'),
        ),
    ]
