# Generated by Django 5.2.1 on 2025-09-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_client', '0001_initial'),
        ('project_profiling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='project_types',
            field=models.ManyToManyField(blank=True, related_name='clients', to='project_profiling.projecttype'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('company_name',)},
        ),
    ]
