# Generated by Django 5.2.1 on 2025-09-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_client', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='xero_contact_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='xero_last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
