# Generated by Django 5.2.1 on 2025-09-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_client', '0003_client_xero_contact_id_client_xero_last_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contract',
            field=models.FileField(blank=True, help_text='Upload client contract (PDF, DOC, DOCX)', null=True, upload_to='contracts/'),
        ),
    ]
