# Generated by Django 5.2.1 on 2025-10-13 14:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('project_profiling', '0011_projectprofile_foreman_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='e.g., Foreman, Laborer, Engineer', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Manpower',
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('ownership_type', models.CharField(choices=[('OWN', 'Owned'), ('RNT', 'Rented')], max_length=3)),
                ('rental_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Daily rental rate (if rented)', max_digits=15, null=True)),
                ('depreciation_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Annual depreciation rate % (if owned)', max_digits=5, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price (if owned)', max_digits=15, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['ownership_type'], name='materials_e_ownersh_5c6b6a_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeneralRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(help_text='e.g., Safety, Tools, Consumables', max_length=100)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(help_text='e.g., set, piece, month', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='materials_e_categor_2a6733_idx')],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(help_text='e.g., kg, meters, pieces', max_length=50)),
                ('standard_price', models.DecimalField(decimal_places=2, help_text='Standard/reference price', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('category', models.CharField(blank=True, help_text='e.g., Cement, Steel, Wood', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['name'], name='materials_e_name_4e3131_idx'), models.Index(fields=['category'], name='materials_e_categor_8254de_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterialPriceMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_type', models.CharField(choices=[('REG', 'Regular Supplier'), ('RND', 'Random Supplier'), ('BTH', 'Both')], max_length=3)),
                ('supplier_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False for outdated prices')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_monitoring', to='materials_equipment.material')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_records', to='authentication.userprofile')),
            ],
            options={
                'ordering': ['-date', 'supplier_type'],
                'indexes': [models.Index(fields=['material', 'date'], name='materials_e_materia_680325_idx'), models.Index(fields=['supplier_type', 'date'], name='materials_e_supplie_158f0f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Actual daily rate for this project', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userprofile')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials_equipment.equipment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_equipment', to='project_profiling.projectprofile')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['project', 'equipment'], name='materials_e_project_eeb3e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectGeneralRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Actual cost for this project', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_general_requirements', to='project_profiling.projectprofile')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials_equipment.generalrequirement')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'requirement'], name='materials_e_project_1ed723_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectManpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of workers')),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Actual daily rate for this project', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userprofile')),
                ('manpower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials_equipment.manpower')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_manpower', to='project_profiling.projectprofile')),
            ],
            options={
                'verbose_name_plural': 'Project Manpower',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['project', 'manpower'], name='materials_e_project_e66272_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Actual price used for this project', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('supplier_type', models.CharField(choices=[('REG', 'Regular Supplier'), ('RND', 'Random Supplier'), ('BTH', 'Both')], max_length=3)),
                ('supplier_name', models.CharField(max_length=200)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userprofile')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials_equipment.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_materials', to='project_profiling.projectprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'material'], name='materials_e_project_50ee86_idx')],
            },
        ),
    ]
